# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
 workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
    
      - name: install r 
        uses: r-lib/actions/setup-r@master


      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: rcmdcheck

      - uses: r-lib/actions/check-r-package@v1

      # Set-up R
      - name: Install packages
        run: |
          R -e 'install.packages("tidyverse")'
          R -e 'install.packages("rvest")'
          R -e 'install.packages("devtools")'
          R -r 'devtools::install_github("uriahf/rtichoke")'
          
    
      - name: Checkout rtichoke
        uses: actions/checkout@v3
        with:
          repository: uriahf/rtichoke
          path: ./rtichoke
          fetch-depth: 0

      # Run R script
    #  - name: Scrape
     #   run: Rscript sitemap_scraping.R


      - name: ls
        run: ls -R

      - name: Upload all
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: data
          # A file, directory or wildcard pattern that describes what to upload
          path: .

