# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
 workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    strategy:
        fail-fast: false
        matrix:
          ind: [0, 1, 2]
    env:
      GITHUB_PAT: ${{ secrets.PAT }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - uses: actions/checkout@v3
        with:
            repository: amir9979/rtichoke_runner
            path: ./runner
            fetch-depth: 0

      - name: create predictions
        run: |
             mkdir ./results
             copy ./classes/prediction_dummy.csv ./results/${{matrix.ind}}.csv
        working-directory: ./runner


      - name: Upload all
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: results
          path: ./runner/results

  aggregate:
      runs-on: windows-latest
      needs: build
      env:
        GITHUB_PAT: ${{ secrets.PAT }}


    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - uses: actions/checkout@v3
        with:
            repository: amir9979/rtichoke_runner
            path: ./runner
            fetch-depth: 0

      - uses: actions/checkout@v3
        with:
            repository: amir9979/rtichoke_runner
            path: ./pages
            fetch-depth: 0
            ref: gh-pages

      - uses: actions/download-artifact@v3
        with:
          name: results
          path: ./runner/results

      - name: install r 
        uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "devtools", "tidyverse"))
          remotes::install_github("uriahf/rtichoke")
        shell: Rscript {0}


      - name: Scrape
        run: Rscript rtichoke_basic.R
        working-directory: ./runner

      - name: ls
        run: ls -R
      
#       - name: gh login
#         run: echo "${{ secrets.PAT }}" | gh auth login --with-token

#       - name: add as gist
#         run: gh gist create --public summary_report.html

      - name: add to pages
        run: |
              git config --global user.email "Amir9979@gmail.com"
              git config --global user.name "Amir9979"
              git add .
              git commit -m "add report"
              git push 
        working-directory: ./pages
