# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
 workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - name: Checkout rtichoke
#         uses: actions/checkout@v3
#         with:
#           repository: uriahf/rtichoke
#           path: .
#           fetch-depth: 0

#       - uses: actions/checkout@v3
#         with:
#             repository: amir9979/rtichoke_runner
#             path: .
#             fetch-depth: 0


      - name: install r 
        uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

#       - uses: r-lib/actions/setup-r-dependencies@v2
#         with:
#           extra-packages: rcmdcheck

#       - uses: r-lib/actions/check-r-package@v2


#       # Set-up R
#       - name: Install packages
#         run: |
#           R -e 'install.packages("devtools")'
#           R -r 'devtools::install_github("uriahf/rtichoke")'

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "devtools"))
          remotes::install_github("uriahf/rtichoke")
        shell: Rscript {0}


#       - uses: r-lib/actions/check-r-package@v2
#         with:
#             args: 'c("--no-manual", "--as-cran")'
#             error-on: '"error"'
#             check-dir: '"check"'
  

#       Run R script
      - name: Scrape
        run: Rscript rtichoke_basic.R


      - name: ls
        run: ls -R

      - name: Upload all
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: data
          # A file, directory or wildcard pattern that describes what to upload
          path: .

