# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
 workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - uses: actions/checkout@v3
        with:
            repository: amir9979/rtichoke_runner
            path: ./runner
            fetch-depth: 0


      - name: install r 
        uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "devtools", "tidyverse"))
          remotes::install_github("uriahf/rtichoke")
        shell: Rscript {0}


      - name: Scrape
        run: Rscript rtichoke_basic.R
        working-directory: ./runner

      - name: ls
        run: ls -R
      
#       - name: gh login
#         run: echo "${{ secrets.PAT }}" | gh auth login --with-token

#       - name: add as gist
#         run: gh gist create --public summary_report.html

      - name: Upload all
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: /summary_report
          # A file, directory or wildcard pattern that describes what to upload
          path: ./runner/summary_report.html

